export OTA_VER

all:
	make -C ./../common/applib/
	make -C ./../common/common_func
	make -C ./../common/bt_common
	make -C ./../common/time_alarm
	make -C ./../common/common_rcp
	make -C ./../common/common_ota
	make -C ./../common/common_view
	make -C ./../common/common_sound
	make -C ./../common/common_event
	make -C ./../common/common_display
	make -C ./../common/aset_common	
	make -C ./../common/data
		
clean:
	make -C ./../common/applib  clean
	make -C ./../common/common_func clean
	make -C ./../common/bt_common clean
	make -C ./../common/time_alarm clean
	make -C ./../common/common_rcp clean
	make -C ./../common/common_ota clean
	make -C ./../common/common_view clean
	make -C ./../common/common_sound clean
	make -C ./../common/common_event clean
	make -C ./../common/common_display clean
	make -C ./../common/aset_common	clean	
	make -C ./../common/data clean
	
clean_target:
	make -C ./../common/applib  clean_target
	make -C ./../common/common_func clean_target
	make -C ./../common/bt_common clean_target
	make -C ./../common/time_alarm clean_target
	make -C ./../common/common_rcp clean_target	
	make -C ./../common/common_ota clean_target
	make -C ./../common/common_view clean_target
	make -C ./../common/common_sound clean_target
	make -C ./../common/common_event clean_target
	make -C ./../common/common_display clean_target
	make -C ./../common/aset_common clean_target		
	make -C ./../common/data clean_target
	