/**
 *******************************************************************************
 * @file    eq_params.c
 * @brief   EQ parameters (type,f0,Q,sqrtA) for the follow EQ styles.
 *          The parameters's data format of (f0, Q, sqrtA) are Q16.0, Q6.10, and
 *          Q6.10 respectively.
 *
 * @author  Auto Generated by Parametric Equalizer Plot Software
 * @version V2.1.0
 *
 * $Created: 2018-01-23T16:15:34$:
 *
 * &copy; Shanghai Mountain View Silicon Technology Co.,Ltd. All rights reserved.
 *******************************************************************************
 */

#include <math.h>
#include "eq.h"
#include "eq_params.h"

typedef struct _EqSet
{
	const uint8_t         Name[EQ_STYLE_CNT][32]; /**< EQ styles name       */
	const EqFilterParams* Params[EQ_STYLE_CNT];   /**< EQ filter parameters */
	const uint8_t         Count0[EQ_STYLE_CNT];   /**< EQ hw filter count   */
	const uint8_t         Count[EQ_STYLE_CNT];    /**< EQ filter count      */
	const uint32_t        Pregain[EQ_STYLE_CNT];  /**< data format Q3.16    */
}EqSet;

//EQ style: Classical
static const EqFilterParams _EqStyle0[4] = 
{
	{ 0x0001, 0x010a, 0x00b7, 0x04a4 }, // Parameters for filter 0
	{ 0x0000, 0x027f, 0x0342, 0x0384 }, // Parameters for filter 1
	{ 0x0000, 0x06ee, 0x02d5, 0x03cc }, // Parameters for filter 2
	{ 0x0002, 0x0eb2, 0x0125, 0x0490 }, // Parameters for filter 4
};

//EQ style: Vocal Booster
static const EqFilterParams _EqStyle1[4] = 
{
	{ 0x0000, 0x0060, 0x01fa, 0x0378 }, // Parameters for filter 1
	{ 0x0000, 0x021f, 0x014d, 0x0480 }, // Parameters for filter 2
	{ 0x0000, 0x09a3, 0x0306, 0x0421 }, // Parameters for filter 3
	{ 0x0002, 0x29e3, 0x02cd, 0x03ce }, // Parameters for filter 4
};

/*
//EQ style: Flat
static const EqFilterParams _EqStyle2[0] = 
{
};
*/

//EQ style: Bass Booster
static const EqFilterParams _EqStyle3[1] = 
{
	{ 0x0001, 0x0082, 0x0221, 0x04b3 }, // Parameters for filter 0
};

//EQ style: Bass Reducer
static const EqFilterParams _EqStyle4[1] = 
{
	{ 0x0001, 0x00e8, 0x026d, 0x0361 }, // Parameters for filter 0
};

//EQ style: Treble Booster
static const EqFilterParams _EqStyle5[1] = 
{
	{ 0x0002, 0x089b, 0x0207, 0x04bb }, // Parameters for filter 4
};

//EQ style: Treble Reducer
static const EqFilterParams _EqStyle6[1] = 
{
	{ 0x0002, 0x0776, 0x02d4, 0x0368 }, // Parameters for filter 4
};

//EQ style: Pop
static const EqFilterParams _EqStyle7[3] = 
{
	{ 0x0001, 0x00cc, 0x0226, 0x03c2 }, // Parameters for filter 0
	{ 0x0000, 0x02ca, 0x01e8, 0x047c }, // Parameters for filter 1
	{ 0x0002, 0x1233, 0x028c, 0x03c8 }, // Parameters for filter 4
};

//EQ style: Rock
static const EqFilterParams _EqStyle8[3] = 
{
	{ 0x0001, 0x00c4, 0x0284, 0x0498 }, // Parameters for filter 0
	{ 0x0000, 0x03c3, 0x0133, 0x03bf }, // Parameters for filter 1
	{ 0x0002, 0x0d8f, 0x0214, 0x0485 }, // Parameters for filter 4
};

//EQ style: Jazz
static const EqFilterParams _EqStyle9[3] = 
{
	{ 0x0001, 0x0070, 0x0185, 0x0483 }, // Parameters for filter 0
	{ 0x0000, 0x0293, 0x036a, 0x03c4 }, // Parameters for filter 2
	{ 0x0002, 0x11d8, 0x0225, 0x0455 }, // Parameters for filter 4
};

//EQ style: R1
static const EqFilterParams _EqStyle10[9] = 
{
	{ 0x0001, 0x0055, 0x02cd, 0x049e }, // Parameters for filter 0
	{ 0x0000, 0x00b4, 0x0400, 0x0351 }, // Parameters for filter 2
	{ 0x0000, 0x0190, 0x0733, 0x0509 }, // Parameters for filter 3
	{ 0x0000, 0x0708, 0x059a, 0x02d5 }, // Parameters for filter 4
	{ 0x0000, 0x0c80, 0x0800, 0x05a6 }, // Parameters for filter 5
	{ 0x0000, 0x0fa0, 0x0666, 0x0556 }, // Parameters for filter 6
	{ 0x0000, 0x1450, 0x0600, 0x02d5 }, // Parameters for filter 7
	{ 0x0000, 0x1f40, 0x099a, 0x04c1 }, // Parameters for filter 8
	{ 0x0000, 0x34bc, 0x0600, 0x04c1 }, // Parameters for filter 9
};

const EqSet EQ_SET = 
{
	{
		"Classical",
		"Vocal Booster",
		"Flat",
		"Bass Booster",
		"Bass Reducer",
		"Treble Booster",
		"Treble Reducer",
		"Pop",
		"Rock",
		"Jazz",
		"R1",
	},
	{
		_EqStyle0,	//Classical
		_EqStyle1,	//Vocal Booster
		NULL,		//Flat
		_EqStyle3,	//Bass Booster
		_EqStyle4,	//Bass Reducer
		_EqStyle5,	//Treble Booster
		_EqStyle6,	//Treble Reducer
		_EqStyle7,	//Pop
		_EqStyle8,	//Rock
		_EqStyle9,	//Jazz
		_EqStyle10,	//R1
	},
	{
		4,
		4,
		0,
		1,
		1,
		1,
		1,
		3,
		3,
		3,
		4,
	},
	{
		4,
		4,
		0,
		1,
		1,
		1,
		1,
		3,
		3,
		3,
		9,
	},
	{
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
		0x00010000,
	}
};

void EqStyleInit(void* SwEQ)
{
   #if   EQ_MODE == 1

   #elif EQ_MODE == 2
   SwEqInit(SwEQ);
   #elif EQ_MODE == 3
   SwEqInit(SwEQ);
   #endif
}

uint8_t* EqStyleNameGet(uint32_t Id)
{
    return (uint8_t*)EQ_SET.Name[Id];
}

void EqStyleSelect(void* SwEQ, uint16_t SamplingRate, uint32_t Id)
{
    #if   EQ_MODE == 1
    EqDisable();
    EqStyleConfigure(SamplingRate, (EqFilterParams*)EQ_SET.Params[Id], EQ_SET.Count[Id], EQ_SET.Pregain[Id]);
    EqEnable();
    #elif EQ_MODE == 2
    SwEqDisable((SwEqContext*)SwEQ);
    SwEqStyleConfigure((SwEqContext*)SwEQ, SamplingRate, (EqFilterParams*)EQ_SET.Params[Id], EQ_SET.Count[Id], EQ_SET.Pregain[Id]);
    SwEqEnable((SwEqContext*)SwEQ);
    #elif EQ_MODE == 3
    EqDisable();
    SwEqDisable((SwEqContext*)SwEQ);
    EqStyleConfigure(SamplingRate, (EqFilterParams*)EQ_SET.Params[Id], EQ_SET.Count0[Id], 0x10000);
    SwEqStyleConfigure((SwEqContext*)SwEQ, SamplingRate, (EqFilterParams*)&EQ_SET.Params[Id][EQ_SET.Count0[Id]], EQ_SET.Count[Id] - EQ_SET.Count0[Id], EQ_SET.Pregain[Id]);
    EqEnable();
    SwEqEnable((SwEqContext*)SwEQ);
    #endif
}

/**
 * @brief EQ style parameters to IIC data
 *
 * @Id  the selected EQ style ID, @see EqStyleSelect
 * @Buf IIC data buffer, max length is EQ_MAX_IIC_DATA_SIZE
 *
 * @return IIC data length, unit in BYTE, max value is EQ_MAX_IIC_DATA_SIZE
 *
 * @note Usage example as follows
 *    //1. Get EQ mode
 *    uint16_t EqMode;//Big Endian
 *    I2cReadNByte(I2cHandle, SlaveAddr, EQ_REG_START_ADDR, &EqMode, 2);
 *
 *    //2. Disable EQ and Config EQ parameters
 *    Len = EqStyleConvert2I2CData(Id, Buf);
 *    I2cWriteNByte(I2cHandle, SlaveAddr, EQ_REG_START_ADDR, Buf, Len);
 *
 *    //3. Enable EQ in EqMode
 *    EqMode &= 0x00C0;
 *    EqMode |= *((uint16_t*)Buf);
 *    I2cWriteNByte(I2cHandle, SlaveAddr, EQ_REG_START_ADDR, &EqMode, 2);
 */
uint32_t EqStyleConvert2I2CData(uint32_t Id, uint8_t Buf[EQ_MAX_IIC_DATA_SIZE])
{
    EqFilterParams* param = (EqFilterParams*)EQ_SET.Params[Id];

    uint32_t  f;
    uint32_t  len = 2 + 2 + 2 * 4 * EQ_SET.Count[Id];
    uint16_t* p   = (uint16_t*)Buf;
    uint8_t   byte;

    *p++ = ((1 << EQ_SET.Count[Id]) - 1) << 1;
    *p++ = (uint16_t)(20 * log10(EQ_SET.Pregain[Id] / 65536.0) * 256.0);

    for(f = 0; f < EQ_SET.Count[Id]; f++)
    {
        *p++ = param[f].type;
        *p++ = param[f].f0;
        *p++ = param[f].Q;
        *p++ = (int16_t)(80 * log10(param[f].sqrtA / 1024.0) * 256 + 0.5);
    }

    for(f = 0; f < len; f += 2)
    {
        byte     = Buf[f+0];
        Buf[f+0] = Buf[f+1];
        Buf[f+1] = byte;
    }

    return len;
}
