/**
 **************************************************************************************
 * @file    app_message.h
 * @brief   
 *
 * @author  halley
 * @version V1.0.0
 *
 * $Created: 2016-6-29 13:06:47$
 *
 * @Copyright (C) 2016, Shanghai Mountain View Silicon Co.,Ltd. All rights reserved.
 **************************************************************************************
 */


#ifndef __APP_MESSAGE_H__
#define __APP_MESSAGE_H__

#include "type.h"
// Task:容器state、MSG; Operation:功能性State、MSG
/*************************************************************************************
 *
 * Message defines
 *
 */

typedef enum 
{
/** generally */
	MSG_NONE,
/** Require down to task(mode app or service) */
	MSG_TASK_CREATE,
	MSG_TASK_START,
	MSG_TASK_RESUME,		//恢复服务，
	MSG_TASK_PAUSE,			//暂停服务，功能复位
	MSG_TASK_STOP,
	MSG_TASK_POWERDOWN,		//PowerKey软开关应用下发送消息在task应用中处理
	MSG_TASK_DEEPSLEEP,		//standby，待机模式，断点处接着运行
	MSG_APP_EXIT,
	MSG_APP_RES_RELEASE,
	MSG_APP_RES_RELEASE_SUC,//释放成功
	MSG_APP_RES_MALLOC,
	MSG_APP_RES_MALLOC_SUC,//申请成功
	MSG_APP_RES_INIT,
	MSG_APP_RES_INIT_SUC,//初始化成功
	
/** Main App*/
	MSG_MAINAPP_GROUP					= 0x0100,
/** Operation Msg */	
	MSG_MAINAPP_NEXT_MODE,
	MSG_MAINAPP_EFFECT_MUTE,

/*****************app msg***********/

/** Media Play Mode -Create by mainapp */
	MSG_STANDBY_PLAY_MODE_GROUP					= 0x0200,
/** Task msg */
	MSG_STANDBY_PLAY_MODE_CREATED,
	MSG_STANDBY_PLAY_MODE_STARTED,
	MSG_STANDBY_PLAY_MODE_PAUSED,
	MSG_STANDBY_PLAY_MODE_STOPPED,
/** Operation Msg */
	MSG_STANDY_PERMISSION_MODE,//允许首个模式启动。


/** Media Play Mode -Create by mainapp */
	MSG_MEDIA_PLAY_MODE_GROUP			= 0x0300,
/** Task msg */
	MSG_MEDIA_PLAY_MODE_CREATED,
	MSG_MEDIA_PLAY_MODE_STARTED,
	MSG_MEDIA_PLAY_MODE_PAUSED,
	MSG_MEDIA_PLAY_MODE_STOPPED,
/** Operation Msg */
	MSG_MEDIA_PLAY_DECODER,
	MSG_MEDIA_PLAY_STOP,
	MSG_MEDIA_PLAY_PLAY_PAUSE,
	MSG_MEDIA_PLAY_MODE,	//播放模式切换
	MSG_MEDIA_PLAY_NEXT,
	MSG_MEDIA_PLAY_NEXT_REMIND, //查询/插播提示音后
	MSG_MEDIA_PLAY_PRE,
	MSG_MEDIA_PLAY_VOLUP,
	MSG_MEDIA_PLAY_VOLDOWN,
	MSG_MEDIA_PLAY_FF,
	MSG_MEDIA_PLAY_FB,
	MSG_MEDIA_PLAY_FF_FB_END,
	MSG_MEDIA_PLAY_FOLDER_PRE,
	MSG_MEDIA_PLAY_FOLDER_NEXT,

/** Disk Mode -Create by mainapp */
	MSG_DISK_AUDIO_MODE_GROUP			= 0x0400,
/** Task msg */
	MSG_DISK_AUDIO_MODE_CREATED,
	MSG_DISK_AUDIO_MODE_STARTED,
	MSG_DISK_AUDIO_MODE_PAUSED,
	MSG_DISK_AUDIO_MODE_STOPPED,
	MSG_MEDIA_PLAY_MODE_FAILURE,
/** Operation Msg */
	MSG_DISK_AUDIO_PLAY_DECODER,
	MSG_DISK_AUDIO_PLAY_PAUSE,
	MSG_DISK_AUDIO_PLAY_STOP,
	MSG_DISK_AUDIO_PLAY_NEXT,
	MSG_DISK_AUDIO_PLAY_PRE,
	MSG_DISK_AUDIO_PLAY_VOLUP,
	MSG_DISK_AUDIO_PLAY_VOLDOWN,

/** BT PLAY Mode -Create by mainapp */
	MSG_BT_PLAY_MODE_GROUP				= 0x0500,
/** Task msg */
	MSG_BT_PLAY_MODE_CREATED,
	MSG_BT_PLAY_MODE_STARTED,
	MSG_BT_PLAY_MODE_PAUSED,
	MSG_BT_PLAY_MODE_STOPPED,
/** Operation Msg */
	MSG_BT_PLAY_PLAY_PAUSE,
	MSG_BT_PLAY_NEXT,
	MSG_BT_PLAY_PRE,
	MSG_BT_PLAY_VOLUP,
	MSG_BT_PLAY_VOLDOWN,
	MSG_BT_PLAY_VOLUME_SET,
	MSG_BT_PLAY_MODE,
	MSG_BT_PLAY_FF,
	MSG_BT_PLAY_FB,
	MSG_BT_PLAY_FF_FB_END,
/*** from bt callback ***/
	MSG_BT_PLAY_DECODER_START,
	MSG_BT_PLAY_STATE_CHANGED,			//A2DP播放状态改变
	MSG_BT_PLAY_SYNC_VOLUME_CHANGED,	//音量同步-音量改变

/** BT HF Mode -Create by mainapp */
	MSG_BT_HF_MODE_GROUP				= 0x0600,
/** Task msg */
	MSG_BT_HF_MODE_CREATED,
	MSG_BT_HF_MODE_STARTED,
	MSG_BT_HF_MODE_PAUSED,
	MSG_BT_HF_MODE_STOPPED,
/** Operation Msg */
	MSG_BT_HF_PLAY_PAUSE,
	MSG_BT_HF_NEXT,
	MSG_BT_HF_PRE,
	MSG_BT_HF_VOLUP,
	MSG_BT_HF_VOLDOWN,
	MSG_BT_HF_TRANS_CHANGED,
	MSG_BT_HF_CALL_REJECT,				//拒接电话
	MSG_BT_HF_REDAIL_LAST_NUM,			//回拨最后来电
	MSG_BT_HF_VOICE_RECOGNITION,		//开启语音助手

/** Line Mode -Create by mainapp */
	MSG_LINE_AUDIO_MODE_GROUP			= 0x0700,
/** Task msg */
	MSG_LINE_AUDIO_MODE_CREATED,
	MSG_LINE_AUDIO_MODE_STARTED,
	MSG_LINE_AUDIO_MODE_PAUSED,
	MSG_LINE_AUDIO_MODE_STOPPED,
	/** Operation Msg */
	MSG_LINE_AUDIO_PLAY_VOLUP,
	MSG_LINE_AUDIO_PLAY_VOLDOWN,
	MSG_LINE_AUDIO_PLAY_EFFECT_MUTE,

/** Hdmi Mode -Create by mainapp */
	MSG_HDMI_AUDIO_MODE_GROUP			= 0x0800,
/** Task msg */
	MSG_HDMI_AUDIO_MODE_CREATED,
	MSG_HDMI_AUDIO_MODE_STARTED,
	MSG_HDMI_AUDIO_MODE_PAUSED,
	MSG_HDMI_AUDIO_MODE_STOPPED,
/** Operation Msg */
	MSG_HDMI_AUDIO_PLAY_PAUSE,
	MSG_HDMI_AUDIO_PLAY_STOP,
	MSG_HDMI_AUDIO_PLAY_NEXT,
	MSG_HDMI_AUDIO_PLAY_PRE,
	MSG_HDMI_AUDIO_PLAY_VOLUP,
	MSG_HDMI_AUDIO_PLAY_VOLDOWN,
	MSG_HDMI_AUDIO_ARC_ONOFF,

/** Spdif Mode -Create by mainapp */
	MSG_SPDIF_AUDIO_MODE_GROUP			= 0x0900,
/** Task msg */
	MSG_SPDIF_AUDIO_MODE_CREATED,
	MSG_SPDIF_AUDIO_MODE_STARTED,
	MSG_SPDIF_AUDIO_MODE_PAUSED,
	MSG_SPDIF_AUDIO_MODE_STOPPED,
/**  Operation Msg */
	MSG_SPDIF_AUDIO_PLAY_PAUSE,
	MSG_SPDIF_AUDIO_PLAY_STOP,
	MSG_SPDIF_AUDIO_PLAY_NEXT,
	MSG_SPDIF_AUDIO_PLAY_PRE,
	MSG_SPDIF_AUDIO_PLAY_VOLUP,
	MSG_SPDIF_AUDIO_PLAY_VOLDOWN,

/** Radio Mode -Create by mainapp */
	MSG_RADIO_AUDIO_MODE_GROUP			= 0x0A00,
/** Task msg */
	MSG_RADIO_AUDIO_MODE_CREATED,
	MSG_RADIO_AUDIO_MODE_STARTED,
	MSG_RADIO_AUDIO_MODE_PAUSED,
	MSG_RADIO_AUDIO_MODE_STOPPED,
/**  Operation Msg */
	MSG_RADIO_PLAY_SCAN,
	MSG_RADIO_PLAY_SCAN_UP,
	MSG_RADIO_PLAY_SCAN_DN,
	MSG_RADIO_PLAY_PRE,
	MSG_RADIO_PLAY_NEXT,

/** USB Device PLAY Mode -Create by mainapp */
	MSG_USB_DEVICE_MODE_GROUP			= 0x0B00,
/** Task msg */
	MSG_USB_DEVICE_MODE_CREATED,
	MSG_USB_DEVICE_MODE_STOPPED,
	MSG_USB_DEVICE_MODE_STARTED,
/**  Operation Msg */
	MSG_DEVICE_SERVICE_USB_DEVICE_IN,
	MSG_DEVICE_SERVICE_USB_DEVICE_OUT,

/** Rtc Mode -Create by mainapp */
	MSG_RTC_MODE_GROUP					= 0x0C00,
/** Task msg */
	MSG_RTC_MODE_CREATED,
	MSG_RTC_MODE_STARTED,
	MSG_RTC_MODE_PAUSED,
	MSG_RTC_MODE_STOPPED,

/** I2SIN Mode -Create by mainapp */
	MSG_I2SIN_AUDIO_MODE_GROUP			= 0x0D00,
/** Task msg */
	MSG_I2SIN_AUDIO_MODE_CREATED,
	MSG_I2SIN_AUDIO_MODE_STARTED,
	MSG_I2SIN_AUDIO_MODE_PAUSED,
	MSG_I2SIN_AUDIO_MODE_STOPPED,
	/** Operation Msg */
	MSG_I2SIN_AUDIO_PLAY_VOLUP,
	MSG_I2SIN_AUDIO_PLAY_VOLDOWN,
	MSG_I2SIN_AUDIO_PLAY_EFFECT_MUTE,


/******************service msg***************/
/** Encoder Service -Create by App */
	MSG_ENCODER_SERVICE_GROUP	= 0x7700,
/** Task msg */
	MSG_ENCODER_SERVICE_CREATED,
	MSG_ENCODER_SERVICE_STARTED,
	MSG_ENCODER_SERVICE_PAUSED,
	MSG_ENCODER_SERVICE_STOPPED,
/** Operation Msg */
	MSG_ENCODER_PLAY,

/** Recorder Service -Create by app */
	MSG_MEDIA_RECORDER_SERVICE_GROUP	= 0x7800,
/** Task msg */
	MSG_MEDIA_RECORDER_SERVICE_CREATED,
	MSG_MEDIA_RECORDER_SERVICE_STARTED,
	MSG_MEDIA_RECORDER_SERVICE_PAUSED,
	MSG_MEDIA_RECORDER_SERVICE_STOPPED,
/** Operation Msg */
	MSG_MEDIA_RECORDER_RUN,
	MSG_MEDIA_RECORDER_STOP,
	MSG_MEDIA_RECORDER_STOPPED,
	MSG_MEDIA_RECORDER_ERROR,

/** Bluetooth Stack service - Create by maintask or app*/
	MSG_BTSTACK_GROUP					= 0x7900,
	MSG_BTSTACK_RX_INT,		//rx data arrival
	MSG_BTSTACK_BB_ERROR,

/** Audio Core Service -Create by maintask */ 
	MSG_AUDIO_CORE_SERVICE_GROUP		= 0x7A00,
/** Task msg */
	MSG_AUDIO_CORE_SERVICE_CREATED,
	MSG_AUDIO_CORE_SERVICE_STARTED,	
	MSG_AUDIO_CORE_SERVICE_PAUSED,
	MSG_AUDIO_CORE_SERVICE_STOPPED,
	MSG_AUDIO_CORE_HOLD,
	MSG_AUDIO_CORE_FRAME_SIZE_CHANGE,
	MSG_AUDIO_CORE_EFFECT_CHANGE,
/** Operation Msg */

/** Remind sound Service -Create by maintask */
	MSG_REMIND_SOUND_SERVICE_GROUP		= 0x7B00,
/** Task msg */
	MSG_REMIND_SOUND_SERVICE_CREATED,
	MSG_REMIND_SOUND_SERVICE_STARTED, 
	MSG_REMIND_SOUND_SERVICE_PAUSED,
	MSG_REMIND_SOUND_SERVICE_STOPPED,
/** Operation Msg */
	MSG_REMIND_SOUND_NEED_DECODER,
	MSG_REMIND_SOUND_ITEM_END,
	MSG_REMIND_SOUND_PLAY_STOPPED,
	MSG_REMIND_SOUND_PLAY_RESET,
	MSG_REMIND_SOUND_PLAY_REQUEST,
	MSG_REMIND_SOUND_PLAY_REQUEST_FAIL,
	MSG_REMIND_SOUND_PLAY,
	MSG_REMIND_SOUND_PLAY_RENEW,
	MSG_REMIND_SOUND_PLAY_START,//一条提示音播放开始
	MSG_REMIND_SOUND_PLAY_DONE,//一条提示音播放结束

/** Decoder Service -Create by mode app */
	MSG_DECODER_SERVICE_GROUP			= 0x7C00,
/** Task msg */
	MSG_DECODER_SERVICE_CREATED,
	MSG_DECODER_SERVICE_STARTED, 
	MSG_DECODER_SERVICE_PAUSED,
	MSG_DECODER_SERVICE_RESUMED,
	MSG_DECODER_SERVICE_STOPPED,
	MSG_DECODER_SERVICE_FREED,
	MSG_DECODER_SERVICE_ERR,
	MSG_DECODER_SERVICE_FIFO_EMPTY,
	MSG_DECODER_SERVICE_SONG_PLAY_END,
	MSG_DECODER_SERVICE_UPDATA_PLAY_TIME,
/** Operation Msg */
	MSG_DECODER_PLAY,
	MSG_DECODER_PAUSE,
	MSG_DECODER_RESUME,
	MSG_DECODER_STOP,
	MSG_DECODER_FF,
	MSG_DECODER_FB,
	MSG_DECODER_RESET,

	MSG_DECODER_STOPPED,
	MSG_DECODER_PLAYING,
	MSG_DECODER_INITED,

/** Playback Service -Create by app */
	MSG_PLAYBACK_SERVICE_GROUP			= 0x7E00,
/** Task msg */
	MSG_PLAYBACK_SERVICE_CREATED,
	MSG_PLAYBACK_SERVICE_STARTED,
	MSG_PLAYBACK_SERVICE_PAUSED,
	MSG_PLAYBACK_SERVICE_STOPPED,
	MSG_PLAYBACK_SERVICE_FREED,
/** Operation Msg */
	MSG_PLAYBACK_PAUSE,
	MSG_PLAYBACK_STOP,
	MSG_PLAYBACK_PLAY,//区别于服务，起始终止，这是回放文件本身Action。
	MSG_PLAYBACK_STOPPED,
	MSG_PLAYBACK_ERROR,

/** Display Service -Create by mainapp */
	/** Task msg */
	MSG_DISPLAY_SERVICE_CREATED,
	MSG_DISPLAY_SERVICE_STARTED,
	MSG_DISPLAY_SERVICE_PAUSED,
	MSG_DISPLAY_SERVICE_STOPPED,
	/** Display Msg */
	MSG_DISPLAY_SERVICE_DEV,
	MSG_DISPLAY_SERVICE_BT_UNLINK,
	MSG_DISPLAY_SERVICE_BT_LINKED,
	MSG_DISPLAY_SERVICE_LINE,
	MSG_DISPLAY_SERVICE_RADIO,
	MSG_DISPLAY_SERVICE_MEDIA,
	MSG_DISPLAY_SERVICE_FILE_NUM,
	MSG_DISPLAY_SERVICE_NUMBER,
	MSG_DISPLAY_SERVICE_STATION,
	MSG_DISPLAY_SERVICE_SEARCH_STATION,
	MSG_DISPLAY_SERVICE_VOL,
	MSG_DISPLAY_SERVICE_MUSIC_VOL,
	MSG_DISPLAY_SERVICE_MIC_VOL,
	MSG_DISPLAY_SERVICE_TRE,
	MSG_DISPLAY_SERVICE_BAS,
	MSG_DISPLAY_SERVICE_3D,
	MSG_DISPLAY_SERVICE_VB,
	MSG_DISPLAY_SERVICE_SHUNNING,
	MSG_DISPLAY_SERVICE_VOCAL_CUT,
	MSG_DISPLAY_SERVICE_MUTE,
	MSG_DISPLAY_SERVICE_EQ,
	MSG_DISPLAY_SERVICE_REPEAT,
	MSG_DISPLAY_SERVICE_PLAY,
	MSG_DISPLAY_SERVICE_PAUSE,
	MSG_DISPLAY_SERVICE_RTC_TIME,
/** Device Service -Create by mainapp */
	MSG_DEVICE_SERVICE_GROUP			= 0x7F00,
/** Task msg */
	MSG_DEVICE_SERVICE_CREATED,
	MSG_DEVICE_SERVICE_STARTED,
	MSG_DEVICE_SERVICE_PAUSED,
	MSG_DEVICE_SERVICE_STOPPED,
/** Operation Msg */
	MSG_DEVICE_SERVICE_LINE_IN,
	MSG_DEVICE_SERVICE_LINE_OUT,
	MSG_DEVICE_SERVICE_CARD_IN,
	MSG_DEVICE_SERVICE_CARD_OUT,
	MSG_DEVICE_SERVICE_CARD_OUT_JITTER,
	MSG_DEVICE_SERVICE_DISK_IN,
	MSG_DEVICE_SERVICE_DISK_OUT,
	//BT CALL MODE
	MSG_DEVICE_SERVICE_BTHF_IN,
	MSG_DEVICE_SERVICE_BTHF_OUT,
	//BT PLAY MODE
	MSG_DEVICE_SERVICE_BTPLAY_IN,
	
	MSG_DEVICE_SERVICE_SWITCH_MODE,
	MSG_DEVICE_SERVICE_BATTERY_DANGER,
	MSG_DEVICE_SERVICE_BATTERY_LOW,
	MSG_DEVICE_SERVICE_BATTERY_MID,
	MSG_DEVICE_SERVICE_BATTERY_HIGH,
	MSG_DEVICE_SERVICE_BATTERY_MAX,
	MSG_DEVICE_SERVICE_PAUSE,
	MSG_DEVICE_SERVICE_STOP,
	MSG_DEVICE_SERVICE_NEXT,
	MSG_DEVICE_SERVICE_PRE,
	MSG_DEVICE_SERVICE_FF,
	MSG_DEVICE_SERVICE_FB,
	MSG_DEVICE_SERVICE_FF_FB_END,
	MSG_DEVICE_SERVICE_VOLUP,
	MSG_DEVICE_SERVICE_VOLDOWN,
	MSG_DEVICE_SERVICE_MUTE,
	MSG_DEVICE_SERVICE_MENU,			//菜单，音量控制等
	MSG_DEVICE_SERVICE_RECORDER,
	MSG_DEVICE_SERVICE_PLAYBACK,
	MSG_DEVICE_SERVICE_REC_DEL,
	MSG_DEVICE_SERVICE_RTC,
	MSG_DEVICE_SERVICE_RTC_SET,
	MSG_DEVICE_SERVICE_RTC_UP,
	MSG_DEVICE_SERVICE_RTC_DOWN,
	MSG_DEVICE_SERVICE_UPDATE,
	MSG_DEVICE_SERVICE_POWERDOWN,			//PowerKey软开关应用下发送消息在task应用中处理
	MSG_DEVICE_SERVICE_DEEPSLEEP,			//待机模式，断点处接着运行
	MSG_DEVICE_SERVICE_SOFT_POWER,          //外部CMOS电路软开关消息
	MSG_DEVICE_SERVICE_BP_SYS_INFO,			//掉电记忆系统信息更新
	MSG_DEVICE_SERVICE_BP_PLAYER_INFO,		//掉电记忆媒体播放信息更新
	MSG_DEVICE_SERVICE_BP_PLAYER_INFO_2NVM,	//掉电记忆媒体播放信息到NVM，需要记忆时间到S
	MSG_DEVICE_SERVICE_BP_RADIO_INFO,		//掉电记忆媒体播放信息更新
	MSG_DEVICE_SERVICE_BP_ALL_INFO,			//掉电记忆所有信息同时更新

	MSG_DEVICE_SERVICE_MUSIC_VOLUP,
	MSG_DEVICE_SERVICE_MUSIC_VOLDOWN,
	MSG_DEVICE_SERVICE_MIC_VOLUP,
	MSG_DEVICE_SERVICE_MIC_VOLDOWN,
	MSG_DEVICE_SERVICE_MIC_EFFECT_UP,
	MSG_DEVICE_SERVICE_MIC_EFFECT_VOLDOWN,
	MSG_DEVICE_SERVICE_VOCAL_CUT,
	MSG_DEVICE_SERVICE_MIC_SHUNNING,
	MSG_DEVICE_SERVICE_TREB_UP,
	MSG_DEVICE_SERVICE_TREB_DW,
	MSG_DEVICE_SERVICE_BASS_UP,
	MSG_DEVICE_SERVICE_BASS_DW,
	MSG_DEVICE_SERVICE_EQ,
	MSG_DEVICE_SERVICE_3D,
	MSG_DEVICE_SERVICE_VB,
	MSG_DEVICE_SERVICE_EFFECTMODE,
	MSG_DEVICE_SERVICE_MUSIC_WHETHER_REC,
    MSG_DEVICE_SERVICE_0,
	MSG_DEVICE_SERVICE_1,
	MSG_DEVICE_SERVICE_2,
	MSG_DEVICE_SERVICE_3,
	MSG_DEVICE_SERVICE_4,
	MSG_DEVICE_SERVICE_5,
	MSG_DEVICE_SERVICE_6,
	MSG_DEVICE_SERVICE_7,
	MSG_DEVICE_SERVICE_8,
	MSG_DEVICE_SERVICE_9,


	MSG_BT_AI,
	MSG_FM_SET,
	MSG_SYS_VOL_UP,
	MSG_MUSIC_MODE,
	MSG_SYS_POWER,
	MSG_MUSIC_MUTE,
	MSG_SYS_VOL_DOWN,

	//连接状态更新,main_task中用于提示音更新
	MSG_BT_STATE_CONNECTED,
	MSG_BT_STATE_DISCONNECT,
	//手动连接/断开蓝牙
	MSG_BT_CONNECT_CTRL,

	//开始播放音乐,如模式切换需求,按照该事件来进行处理
	MSG_BT_A2DP_STREAMING,

/******************adc level ,Sliding resistance msg, Reservations***************/
    MSG_ADC_LEVEL_MSG_START       = 0x9000,
    MSG_ADC_LEVEL_CH1             = 0x9100,
    MSG_ADC_LEVEL_CH2             = 0x9200,
    MSG_ADC_LEVEL_CH3             = 0x9300,
	MSG_ADC_LEVEL_CH4             = 0x9400,
	MSG_ADC_LEVEL_CH5             = 0x9500,
	MSG_ADC_LEVEL_CH6             = 0x9600,
	MSG_ADC_LEVEL_CH7             = 0x9700,
	MSG_ADC_LEVEL_CH8             = 0x9800,
	MSG_ADC_LEVEL_CH9             = 0x9900,
	MSG_ADC_LEVEL_CH10            = 0x9a00,
	MSG_ADC_LEVEL_CH11            = 0x9b00,
	MSG_ADC_LEVEL_CH12            = 0x9c00,
	MSG_ADC_LEVEL_CH13            = 0x9d00,
	MSG_ADC_LEVEL_CH14            = 0x9e00,
	MSG_ADC_LEVEL_MSG_END         = 0x9f00,   
} MessageId;

#define MAX_RECV_MSG_TIMEOUT		0xFFFFFFFF


/*************************************************************************************
 *
 * Module Message defines
 *
 *************************************************************************************/

typedef enum
{
	TaskStateNone	= 0,
	TaskStateCreating,
	TaskStateReady, // TaskStateCreated
	TaskStateStarting,
	TaskStateRunning, // TaskStateStarted
	TaskStatePausing,
	TaskStatePaused,
	TaskStateResuming,
	TaskStateStopping,
	TaskStateStopped,
	TaskStateError,
}TaskState;

#endif /*__APP_MESSAGE_H__*/

