/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Mon May 28 19:35:37 2018. */

#include "message.h"

#ifdef NANOPB_TEST

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const pb_field_t SimpleMessage_fields[2] = {
    PB_FIELD(1, INT32, REQUIRED, STATIC, FIRST, SimpleMessage, lucky_number, lucky_number, 0),
    PB_LAST_FIELD
};
#endif
/* @@protoc_insertion_point(eof) */
