
obj-y := dma_protobuf/ dma_stream/ dma_manager/



subdir-ccflags-y += -Iapps/apptester \
					-Iapps/audioplayers \
					-Iapps/common \
					-Iapps/main \
					-Iapps/key \
					-Iapps/pwl \
					-Iservices/multimedia/opus121/include \
					-Iservices/bt_app \
					-Iutils/list \
					-Iservices/bt_app/app_voice/app_bt_ama \
					-Iservices/ble_stack/ble_ip \
					-Iservices/ble_stack/hl/api \
					-Iservices/ble_stack/ke/api \
					-Iservices/ble_stack/common/api \
					-Iservices/ai_voice/dma \
					-Iservices/bt_app/app_voice/app_bt_dma
		
