#ifndef FUNC_SINGLE_LED_H
#define FUNC_SINGLE_LED_H

typedef enum _LED_DISP_STATE
{
	LED_DISP_STATE_IDLE = 0,
	LED_DISP_STATE_WHITE,
	LED_DISP_STATE_RED,
	LED_DISP_STATE_CHREGERED,
	LED_DISP_STATE_GREEN,
	LED_DISP_STATE_BLUE,
  LED_DISP_STATE_ALL,
} LED_DISP_STATE;

extern void SingLedDispStateSet(LED_DISP_STATE DispState, bool State);

#endif

