.PHONY: clean All

All:
	@echo "----------Building project:[ MXQ - BuildSet ]----------"
	@cd "MXQ" && make -f  "MXQ.mk"
clean:
	@echo "----------Cleaning project:[ MXQ - BuildSet ]----------"
	@cd "MXQ" && make -f  "MXQ.mk" clean
