.PHONY: clean All

All:
	@echo "----------Building project:[ HF30M - BuildSet ]----------"
	@cd "HF30M" && make -f  "HF30M.mk"
clean:
	@echo "----------Cleaning project:[ HF30M - BuildSet ]----------"
	@cd "HF30M" && make -f  "HF30M.mk" clean
