.PHONY: clean All

All:
	@echo "----------Building project:[ KS_taideng - BuildSet ]----------"
	@cd "KS_taideng" && make -f  "KS_taideng.mk"
clean:
	@echo "----------Cleaning project:[ KS_taideng - BuildSet ]----------"
	@cd "KS_taideng" && make -f  "KS_taideng.mk" clean
