#include "include.h"

#if (LANG_SELECT == LANG_EN_ZH)
const res_addr_t mul_lang_tbl[2][IDX_MAX_MP3] = {
    {
        [IDX_LANGUAGE_MP3   ] = {&RES_BUF_EN_LANGUAGE_MP3,      &RES_LEN_EN_LANGUAGE_MP3},
        [IDX_LOW_BATTERY_MP3] = {&RES_BUF_EN_LOW_BATTERY_MP3,   &RES_LEN_EN_LOW_BATTERY_MP3},
        [IDX_POWERON_MP3    ] = {&RES_BUF_EN_POWERON_MP3,       &RES_LEN_EN_POWERON_MP3},
        [IDX_POWEROFF_MP3   ] = {&RES_BUF_EN_POWEROFF_MP3,      &RES_LEN_EN_POWEROFF_MP3},
//        [IDX_MAX_VOL_MP3    ] = {&RES_BUF_EN_MAX_VOL_MP3,       &RES_LEN_EN_MAX_VOL_MP3},
//        [IDX_SDCARD_MODE_MP3] = {&RES_BUF_EN_SDCARD_MODE_MP3,   &RES_LEN_EN_SDCARD_MODE_MP3},
//        [IDX_USB_MODE_MP3   ] = {&RES_BUF_EN_USB_MODE_MP3,      &RES_LEN_EN_USB_MODE_MP3},
        [IDX_AUX_MODE_MP3   ] = {&RES_BUF_EN_AUX_MODE_MP3,      &RES_LEN_EN_AUX_MODE_MP3},
//        [IDX_CLOCK_MODE_MP3 ] = {&RES_BUF_EN_CLOCK_MODE_MP3,    &RES_LEN_EN_CLOCK_MODE_MP3},
//        [IDX_FM_MODE_MP3    ] = {&RES_BUF_EN_FM_MODE_MP3,       &RES_LEN_EN_FM_MODE_MP3},
//        [IDX_SPK_MODE_MP3   ] = {&RES_BUF_EN_SPK_MODE_MP3,      &RES_LEN_EN_SPK_MODE_MP3},
//        [IDX_PC_MODE_MP3    ] = {&RES_BUF_EN_PC_MODE_MP3,       &RES_LEN_EN_PC_MODE_MP3},
        [IDX_BT_MODE_MP3    ] = {&RES_BUF_EN_BT_MODE_MP3,       &RES_LEN_EN_BT_MODE_MP3},
        [IDX_CAMERA_MODE_MP3] = {&RES_BUF_EN_CAMERA_MODE_MP3,   &RES_LEN_EN_CAMERA_MODE_MP3},
        [IDX_LEFT_CH_MP3    ] = {&RES_BUF_EN_LEFT_CH_MP3,       &RES_LEN_EN_LEFT_CH_MP3},
        [IDX_RIGHT_CH_MP3   ] = {&RES_BUF_EN_RIGHT_CH_MP3,     &RES_LEN_EN_RIGHT_CH_MP3},
        [IDX_PAIRING_MP3    ] = {&RES_BUF_EN_PAIRING_MP3,      &RES_LEN_EN_PAIRING_MP3},
        [IDX_WAIT4CONN_MP3  ] = {&RES_BUF_EN_WAIT4CONN_MP3,    &RES_LEN_EN_WAIT4CONN_MP3},
        [IDX_CONNECTED_MP3  ] = {&RES_BUF_EN_CONNECTED_MP3,    &RES_LEN_EN_CONNECTED_MP3},
        [IDX_DISCONNECT_MP3 ] = {&RES_BUF_EN_DISCONNECT_MP3,   &RES_LEN_EN_DISCONNECT_MP3},
        [IDX_CAMERA_ON_MP3  ] = {&RES_BUF_EN_CAMERA_ON_MP3,    &RES_LEN_EN_CAMERA_ON_MP3},
        [IDX_CAMERA_OFF_MP3 ] = {&RES_BUF_EN_CAMERA_OFF_MP3,   &RES_LEN_EN_CAMERA_OFF_MP3},
        [IDX_CALL_HANGUP_MP3] = {&RES_BUF_EN_CALL_HANGUP_MP3,  &RES_LEN_EN_CALL_HANGUP_MP3},
        [IDX_CALL_REJECT_MP3] = {&RES_BUF_EN_CALL_REJECT_MP3,  &RES_LEN_EN_CALL_REJECT_MP3},
        [IDX_REDIALING_MP3  ] = {&RES_BUF_EN_REDIALING_MP3,    &RES_LEN_EN_REDIALING_MP3},
        [IDX_NUM_0_MP3      ] = {&RES_BUF_EN_NUM_0_MP3,        &RES_LEN_EN_NUM_0_MP3},
        [IDX_NUM_1_MP3      ] = {&RES_BUF_EN_NUM_1_MP3,        &RES_LEN_EN_NUM_1_MP3},
        [IDX_NUM_2_MP3      ] = {&RES_BUF_EN_NUM_2_MP3,        &RES_LEN_EN_NUM_2_MP3},
        [IDX_NUM_3_MP3      ] = {&RES_BUF_EN_NUM_3_MP3,        &RES_LEN_EN_NUM_3_MP3},
        [IDX_NUM_4_MP3      ] = {&RES_BUF_EN_NUM_4_MP3,        &RES_LEN_EN_NUM_4_MP3},
        [IDX_NUM_5_MP3      ] = {&RES_BUF_EN_NUM_5_MP3,        &RES_LEN_EN_NUM_5_MP3},
        [IDX_NUM_6_MP3      ] = {&RES_BUF_EN_NUM_6_MP3,        &RES_LEN_EN_NUM_6_MP3},
        [IDX_NUM_7_MP3      ] = {&RES_BUF_EN_NUM_7_MP3,        &RES_LEN_EN_NUM_7_MP3},
        [IDX_NUM_8_MP3      ] = {&RES_BUF_EN_NUM_8_MP3,        &RES_LEN_EN_NUM_8_MP3},
        [IDX_NUM_9_MP3      ] = {&RES_BUF_EN_NUM_9_MP3,        &RES_LEN_EN_NUM_9_MP3},
    },
    {
        [IDX_LANGUAGE_MP3   ] = {&RES_BUF_ZH_LANGUAGE_MP3,     &RES_LEN_ZH_LANGUAGE_MP3},
        [IDX_LOW_BATTERY_MP3] = {&RES_BUF_ZH_LOW_BATTERY_MP3,  &RES_LEN_ZH_LOW_BATTERY_MP3},
        [IDX_POWERON_MP3    ] = {&RES_BUF_ZH_POWERON_MP3,      &RES_LEN_ZH_POWERON_MP3},
        [IDX_POWEROFF_MP3   ] = {&RES_BUF_ZH_POWEROFF_MP3,     &RES_LEN_ZH_POWEROFF_MP3},
//        [IDX_MAX_VOL_MP3    ] = {&RES_BUF_ZH_MAX_VOL_MP3,      &RES_LEN_ZH_MAX_VOL_MP3},
//        [IDX_SDCARD_MODE_MP3] = {&RES_BUF_ZH_SDCARD_MODE_MP3,  &RES_LEN_ZH_SDCARD_MODE_MP3},
//        [IDX_USB_MODE_MP3   ] = {&RES_BUF_ZH_USB_MODE_MP3,     &RES_LEN_ZH_USB_MODE_MP3},
//        [IDX_AUX_MODE_MP3   ] = {&RES_BUF_ZH_AUX_MODE_MP3,     &RES_LEN_ZH_AUX_MODE_MP3},
//        [IDX_CLOCK_MODE_MP3 ] = {&RES_BUF_ZH_CLOCK_MODE_MP3,   &RES_LEN_ZH_CLOCK_MODE_MP3},
//        [IDX_FM_MODE_MP3    ] = {&RES_BUF_ZH_FM_MODE_MP3,      &RES_LEN_ZH_FM_MODE_MP3},
//        [IDX_SPK_MODE_MP3   ] = {&RES_BUF_ZH_SPK_MODE_MP3,     &RES_LEN_ZH_SPK_MODE_MP3},
//        [IDX_PC_MODE_MP3    ] = {&RES_BUF_ZH_PC_MODE_MP3,      &RES_LEN_ZH_PC_MODE_MP3},
        [IDX_BT_MODE_MP3    ] = {&RES_BUF_ZH_BT_MODE_MP3,      &RES_LEN_ZH_BT_MODE_MP3},
        [IDX_CAMERA_MODE_MP3] = {&RES_BUF_ZH_CAMERA_MODE_MP3,  &RES_LEN_ZH_CAMERA_MODE_MP3},
        [IDX_LEFT_CH_MP3    ] = {&RES_BUF_ZH_LEFT_CH_MP3,      &RES_LEN_ZH_LEFT_CH_MP3},
        [IDX_RIGHT_CH_MP3   ] = {&RES_BUF_ZH_RIGHT_CH_MP3,     &RES_LEN_ZH_RIGHT_CH_MP3},
        [IDX_PAIRING_MP3    ] = {&RES_BUF_ZH_PAIRING_MP3,      &RES_LEN_ZH_PAIRING_MP3},
        [IDX_WAIT4CONN_MP3  ] = {&RES_BUF_ZH_WAIT4CONN_MP3,    &RES_LEN_ZH_WAIT4CONN_MP3},
        [IDX_CONNECTED_MP3  ] = {&RES_BUF_ZH_CONNECTED_MP3,    &RES_LEN_ZH_CONNECTED_MP3},
        [IDX_DISCONNECT_MP3 ] = {&RES_BUF_ZH_DISCONNECT_MP3,   &RES_LEN_ZH_DISCONNECT_MP3},
        [IDX_CAMERA_ON_MP3  ] = {&RES_BUF_ZH_CAMERA_ON_MP3,    &RES_LEN_ZH_CAMERA_ON_MP3},
        [IDX_CAMERA_OFF_MP3 ] = {&RES_BUF_ZH_CAMERA_OFF_MP3,   &RES_LEN_ZH_CAMERA_OFF_MP3},
        [IDX_CALL_HANGUP_MP3] = {&RES_BUF_ZH_CALL_HANGUP_MP3,  &RES_LEN_ZH_CALL_HANGUP_MP3},
        [IDX_CALL_REJECT_MP3] = {&RES_BUF_ZH_CALL_REJECT_MP3,  &RES_LEN_ZH_CALL_REJECT_MP3},
        [IDX_REDIALING_MP3  ] = {&RES_BUF_ZH_REDIALING_MP3,    &RES_LEN_ZH_REDIALING_MP3},
        [IDX_NUM_0_MP3      ] = {&RES_BUF_ZH_NUM_0_MP3,        &RES_LEN_ZH_NUM_0_MP3},
        [IDX_NUM_1_MP3      ] = {&RES_BUF_ZH_NUM_1_MP3,        &RES_LEN_ZH_NUM_1_MP3},
        [IDX_NUM_2_MP3      ] = {&RES_BUF_ZH_NUM_2_MP3,        &RES_LEN_ZH_NUM_2_MP3},
        [IDX_NUM_3_MP3      ] = {&RES_BUF_ZH_NUM_3_MP3,        &RES_LEN_ZH_NUM_3_MP3},
        [IDX_NUM_4_MP3      ] = {&RES_BUF_ZH_NUM_4_MP3,        &RES_LEN_ZH_NUM_4_MP3},
        [IDX_NUM_5_MP3      ] = {&RES_BUF_ZH_NUM_5_MP3,        &RES_LEN_ZH_NUM_5_MP3},
        [IDX_NUM_6_MP3      ] = {&RES_BUF_ZH_NUM_6_MP3,        &RES_LEN_ZH_NUM_6_MP3},
        [IDX_NUM_7_MP3      ] = {&RES_BUF_ZH_NUM_7_MP3,        &RES_LEN_ZH_NUM_7_MP3},
        [IDX_NUM_8_MP3      ] = {&RES_BUF_ZH_NUM_8_MP3,        &RES_LEN_ZH_NUM_8_MP3},
        [IDX_NUM_9_MP3      ] = {&RES_BUF_ZH_NUM_9_MP3,        &RES_LEN_ZH_NUM_9_MP3},
    },
};

void multi_lang_init(uint lang_id)
{
}

const res_addr_t *res_get_ring_num(u8 index)
{
    return &mul_lang_tbl[sys_cb.lang_id][index+IDX_NUM_0_MP3];
}

#endif //#if (LANG_SELECT == LANG_EN_ZH)
